apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-public

resources:
  - ../../base
  - ingress.yaml

images:
  - name: registry.lantern.diiage/lantern/frontend-public
    newTag: dev-latest
