apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rewards
namePrefix: rewards-

resources:
  - ../../../_bases/dotnet-postgres

patches:
  - path: settings.yaml

images:
  - name: registry.lantern.diiage/lantern/backend
    newName: registry.lantern.diiage/lantern/reward-backend
    newTag: dev-latest
