apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dungeon
namePrefix: dungeon-

resources:
  - ../../../_bases/dotnet-postgres

patches:
  - path: settings.yaml

images:
  - name: registry.lantern.diiage/lantern/backend
    newName: registry.lantern.diiage/lantern/dungeon-backend
    newTag: dev-562bde677f05
