apiVersion: v1
kind: Service
metadata:
  name: frontend-public
spec:
  selector:
    app.kubernetes.io/name: frontend-public
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-public
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-public
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-public
    spec:
      imagePullSecrets:
        - name: harbor-pull
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend-public
          image: registry.lantern.diiage/lantern/frontend-public
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NUXT_PUBLIC_API_GATEWAY_URL
              value: http://player.lantern.diiage
            - name: NUXT_PUBLIC_SITE_URL
              value: http://public.lantern.diiage
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 384Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 3
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 20
