deployment:
  replicas: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

service:
  type: LoadBalancer

ports:
  web:
    port: 8000
    exposedPort: 80
    expose:
      default: true
  websecure:
    port: 8443
    exposedPort: 443
    expose:
      default: true

providers:
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
    publishedService:
      enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
        topologyKey: kubernetes.io/hostname

log:
  level: INFO

accessLog:
  enabled: true

resources:
  requests: {cpu: 200m, memory: 256Mi}
  limits: {cpu: "1", memory: 1Gi}
