apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: progression
namePrefix: progression-

resources:
  - ../../../_bases/dotnet-postgres

patches:
  - path: settings.yaml

images:
  - name: registry.lantern.diiage/lantern/backend
    newName: registry.lantern.diiage/lantern/leaderboard-backend
    newTag: dev-8f3995e9da0a
